#!/usr/bin/env bash
# configure domain and sub domain zones

domain="$1"
subdomain="$2"

# function to print out results
print_info(){
	text=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:')
	record_type=$(echo "$text" | awk '{printf $4}')
	destination=$(echo "$text" | awk '{printf $5}')
	echo "The subdomain $subdomain is a $record_type record and points to $destination"

}

if [ $# -eq 1 ]; then
	# www domain
	subdomain="www"
	print_info "$domain" "$subdomain"

	# lb-01 subdomain
	subdomain="lb-01"
	print_info "$domain" "$subdomain"

	# web-01 subdomain
	subdomain="web-01"
	print_info "$domain" "$subdomain"

	# web-02 subdomain
	subdomain="web-02"
	print_info "$domain" "$subdomain"

elif [ $# -ge 2 ]; then
	# print domain subdomain data
	print_info "$domain" "$subdomain"
else 
	echo "Usage:./0-world_wide_web domain subdmain"
fi
