#!/usr/bin/env bash
# configure domain and sub domain zones

domain="$1"
subdomain="$2"

if [ $# -eq 1 ]; then
	# www domain
	text=$(dig "www.${domain}" | grep -A1 'ANSWER SECTION:'  > /dev/null)
	echo "$text"
	record_type=$(echo "$text" | awk '{printf $4}')
	destination=$(echo "$text" | awk '{printf $5}')
	echo "The subdomain www is a $record_type record and points to $destination"

	# lb-01 subdomain
	text=$(dig "lb-01.${domain}" | grep -A1 'ANSWER SECTION:')
	record_type=$(echo "$text" | awk '{printf $4}')
	destination=$(echo "$text" | awk '{printf $5}')
	echo "The subdomain lb-01 is a $record_type record and points to $destination"

	# web-01 subdomain
	text=$(dig "web-01.${domain}" | grep -A1 'ANSWER SECTION:')
	record_type=$(echo "$text" | awk '{printf $4}')
	destination=$(echo "$text" | awk '{printf $5}')
	echo "The subdomain web-01 is a $record_type record and points to $destination"
	
	# web-02 subdomain
	text=$(dig "web-02.${domain}" | grep -A1 'ANSWER SECTION:' > /dev/null)
	record_type=$(echo "$text" | awk '{printf $4}')
	destination=$(echo "$text" | awk '{printf $5}')
	echo "The subdomain web-02 is a $record_type record and points to $destination"
elif [ $# -ge 2 ]; then
	text=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:')
	record_type=$(echo "$text" | awk '{printf $4}')
	destination=$(echo "$text" | awk '{printf $5}')
	echo "The subdomain ${subdomain} is a $record_type record and points to $destination"
else 
	echo "Usage:./0-world_wide_web domain subdmain"
fi

print_info() {
    local name="$1"
    local age="$2"
    
    echo "Name: $name"
    echo "Age: $age"
}

# Example usage of the function
