#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Requirements:

# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
# Using what you did with 1-install_nginx_web_server, write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task

# update current install package list
apt -y update

# install nginx webserver with apt package manager
apt -y install nginx

# preparing content of page to serve in root directory with GET request
echo "Hello World!" > /var/www/html/index.html



# configure /redirect_me to redirect to another page
redirect_config="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

# using sed -i inline edit option to append configuration after server_name _; pattern
sed -i "/server_name _;/a\ $redirect_config" /etc/nginx/sites-available/default

# restart nginx server 
service nginx restart