#!/usr/bin/env bash
# script to create compressed backup of database

# creating a databse backup from all databases
mysqldump -u root -p"$1" --all-databases > backup.sql

# generate file name from current date
filename="$(date +'%d-%m-%Y').tar.gz"

# generate the achive file with tar util
tar -czvf "${filename}" backup.sql
