#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80. Feel free to install whatever tool you need, start and destroy as many containers as you need to debug the issue. Then, write a Bash script with the minimum number of commands to automate your fix.

# Requirements:

# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# Write a Bash script that configures a server to the above requirements

# enable the default site block by creatings symbolic link of default file in /etc/nginx/sites-enebled/
ln -sf /etc/nginx/sites-available/ /etc/nginx/sites-enabled/

# run nginx
sudo service nginx start
