#!/usr/bin/env bash
# script to get Apache to run on the container and to 
# return a page containing
# Hello Holberton when querying the root of it.

# this commented code below automatical runs container and configures properly
# by starting apache2 service

# container_ID=$(docker run -p 8080:80 -d -it holbertonschool/265-0)
# docker exec "$container_ID" service apache2 start
service apache2 start
