#!/usr/bin/env bash
# program to configure server for nginx to be run by user
# nginx instead of the default root user

# start by stoping  nginx if running 
service nginx stop

# modify /etc/nginx/nginx.conf to allow user nginx
sed -i "/#user www-data;/a\user nginx;" /etc/nginx/nginx.conf

# change owner of nginx folder to nginx
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /var/lib/nginx

# configure nginx to listent on port 8080 for all ips
sed -i "/listen 80 default_server;/a\ \tlisten 8080;" /etc/nginx/sites-available/default

# give atleast read privilleges /etc/nginx/nginx.conf
chmod +r /etc/nginx/nginx.conf

# run the service as nginx user
sudo -u nginx service nginx start
