#!/usr/bin/env bash
# program to configure server for nginx to be run by usernginx instead of the default root user
sed -i "/#user www-data;/a\user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
