#!/usr/bin/env bash
# script to gracefully reload gunicorn without disruption
# script searches for gunicorn master process and sends Hangup signal(HUP)
# which triggers the gracefull killing of worker processes and provisioning of new workers
# with the new configuration information
# pgrep '[g]unicorn' | awk '{print $2}' | xargs kill -HUP
pkill -HUP -f "gunicorn"
